<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-HUTLBGH" name="Login Test" tests="4" failures="1" timestamp="16 Oct 2019 21:57:36 GMT" time="0.1" errors="0">
  <testcase name="doForgotPassword" time="0.016" classname="testngpackage3.GmailLoginTests"/>
  <testcase name="doLogin" time="0.001" classname="testngpackage3.GmailLoginTests"/>
  <testcase name="doResetPassword" time="0.002" classname="testngpackage3.GmailLoginTests"/>
  <testcase name="doSignup" time="0.011" classname="testngpackage3.GmailLoginTests">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at testngpackage3.GmailLoginTests.doSignup(GmailLoginTests.java:32)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- doSignup -->
</testsuite> <!-- Login Test -->
